org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=false
kotlin.code.style=official
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
org.gradle.caching=false
android.compileSdkVersion=36
